de_camp_dbt:
  outputs:
    dev:
      dataset: dbt
      fixed_retries: 1
      keyfile: "./dbt_profiles/cred.json"
      location: ASIA
      method: service-account
      priority: interactive
      project: dzc-trietle
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev